dataset:
  train:
    path: data/train.csv
  val:
    path: data/val.csv
  test:
    path: data/test.csv

  train_feature: ['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
                  'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
                  'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']
  target: 'Class'


#data preprocesing
preprocesing:
  scaler_type: robsut  #stander , minmax

balanceing:
  do_balance: True
  method: under_vs_over # smote under_vs_over under
  sampling_starategy: 0.05


randomseed: 43

focal_loss:
  alpha: 0.25
  gamma: 2.0
  batch_size: 64
  lr: 0.001


  

    